---
- hosts: localhost
  become: yes
  vars:
    - docker_compose_version: '1.29.2'

  tasks:
    - name: Install system packages
      dnf: 
        name:
          - curl
          - ca-certificates
          - dnf-plugins-core
          - flatpak
          - nano
          - git
          - bat
          - exa
          - podman
          - buildah
          - python3-pip
        state: latest

    - name: Install Python packages
      pip:
        name:
          - poetry
        state: latest

    ## Install Web Browsers
    - name: Install Chromium and Chrome Web Browser
      dnf:
        name:
          - chromium
          - fedora-workstation-repositories
          - google-chrome-stable
        enablerepo: google-chrome
        state: latest

    ## Install Skype
    - name: Add skype repository
      yum_repository:
        name: skype-stable
        description: Skype YUM Repo
        baseurl: https://repo.skype.com/rpm/stable
        gpgcheck: true
        gpgkey: "https://repo.skype.com/data/SKYPE-GPG-KEY"

    - name: Install Skype
      dnf:
        name: skypeforlinux
        state: latest

    ## Install Docker and Docker Compose
    - name: "Add Docker's official GPG key"
      rpm_key:
        state: present
        key: https://download.docker.com/linux/fedora/gpg
        fingerprint: 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35
      tags:
        - docker

    - name: Add docker repository
      yum_repository:
        name: docker-ce
        description: Docker YUM Repo
        baseurl: https://download.docker.com/linux/fedora
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/fedora/gpg"

    - name: Install docker
      dnf: 
        name:
          - dnf-plugins-core
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
      tags:
        - docker

    - name: Install docker-compose
      remote_user: ubuntu
      get_url: 
        url : "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

