---
- hosts: localhost
  become: yes
  vars:
    - docker_compose_version: '1.29.2'

  tasks:
    - name: Install system packages
      dnf:
        name:
          - curl
          - ca-certificates
          - dnf-plugins-core
          - flatpak
          - snapd
          - git
          - bat
          - exa
          - python3-pip
        state: latest

    - name: Install Python packages
      pip:
        name:
          - poetry
          - podman-compose
        state: latest

    ## Install Utilities
    - name: Install basic utilies
      dnf:
        name:
          - htop
          - bpytop
          - neofetch
          - ncdu
          - nano
          - foliate
          - podman
          - buildah
        state: latest

    - name: Create a symbolic link for snap
      file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link

    - name: Install MailSpring using Snap
      snap:
        name: mailspring
        state: present

    ## Install BitWarden
    - name: Install BitWarden using Snap
      snap:
        name: bitwarden
        state: present

    ## Install IntelliJ Community Edition
    - name: Install IntelliJ using Snap
      snap:
        name: intellij-idea-community
        classic: yes
        state: present

    ## Install DataGrip Community Edition
    - name: Install DataGrip using Snap
      snap:
        name: datagrip
        classic: yes
        state: present

    ## Install Zoom
    - name: Add Zoom signing key
      rpm_key:
        key: "https://zoom.us/linux/download/pubkey"
        state: present
    - name: Install Zoom with RPM
      dnf:
        name: https://zoom.us/client/latest/zoom_x86_64.rpm
        state: present

    ## Install Microsoft Teams
    - name: Add Microsoft Teams signing key
      rpm_key:
        key: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present
    - name: Add Microsoft Teams Repo
      yum_repository:
        name: teams
        description: teams
        baseurl: "https://packages.microsoft.com/yumrepos/ms-teams/"
        enabled: true
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    - name: Install Microsoft Teams
      dnf:
        name: "teams"
        state: latest

    ## Install Web Browsers
    - name: Install Chrome Web Browser
      dnf:
        name:
          - fedora-workstation-repositories
          - google-chrome-stable
        enablerepo: google-chrome
        state: latest

    ## Install Microsoft Edge
    - name: Add Microsoft Edge signing key
      rpm_key:
        key: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present
    - name: Add Microsoft Edge repository
      yum_repository:
        name: microsoft-edge
        description: microsoft-edge
        baseurl: "https://packages.microsoft.com/yumrepos/edge/"
        enabled: true
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    - name: Install Microsoft Edge
      dnf:
        name: "microsoft-edge-stable"
        state: latest

    ## Install Librewolf
    - name: Install Librewolf repository
      yum_repository:
        name: librewolf
        description: Skype YUM Repo
        baseurl: https://rpm.librewolf.net
        gpgcheck: true
        gpgkey: "https://keys.openpgp.org/vks/v1/by-fingerprint/034F7776EF5E0C613D2F7934D29FBD5F93C0CFC3"

    - name: Install Librewolf Web Browser
      dnf:
        name: librewolf
        state: latest

    ## Install Skype
    - name: Add Skype repository
      yum_repository:
        name: skype-stable
        description: Skype YUM Repo
        baseurl: https://repo.skype.com/rpm/stable
        gpgcheck: true
        gpgkey: "https://repo.skype.com/data/SKYPE-GPG-KEY"

    - name: Install Skype
      dnf:
        name: skypeforlinux
        state: latest

    ## Install Microsoft Visual Studio Code
    - name: Add Visual Studio Code repository
      yum_repository:
        name: vscode
        description: VS Code YUM Repo
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"

    - name: Install Visual Studio Code
      dnf:
        name: code
        state: latest

    # - name: Add ansible-pull cron job
    #   cron:
    #     name: ansible auto-provision
    #     user: jagdeep
    #     minute: "*/10"
    #     job: ansible-pull -o -U https://github.com/jagdeep/ansible.git
