---
- hosts: localhost
  become: yes
  vars:
    - docker_compose_version: '1.29.2'

  tasks:
    - name: Install system packages
      dnf:
        name:
          - curl
          - ca-certificates
          - dnf-plugins-core
          - flatpak
          - git
          - bat
          - exa
          - python3-pip
        state: latest

    - name: Install Python packages
      pip:
        name:
          - poetry
        state: latest

    ## Install Utilities
    - name: Install basic utilies
      dnf:
        name:
          - htop
          - bpytop
          - neofetch
          - ncdu
          - nano
          - podman
          - buildah
        state: latest

    ## Install Web Browsers
    - name: Install Chrome Web Browser
      dnf:
        name:
          - fedora-workstation-repositories
          - google-chrome-stable
        enablerepo: google-chrome
        state: latest

    - name: Install Librewolf repository
      yum_repository:
        name: librewolf
        description: Skype YUM Repo
        baseurl: https://rpm.librewolf.net
        gpgcheck: true
        gpgkey: "https://keys.openpgp.org/vks/v1/by-fingerprint/034F7776EF5E0C613D2F7934D29FBD5F93C0CFC3"

    - name: Install Librewolf Web Browser
      dnf:
        name: librewolf
        state: latest

    ## Install Skype
    - name: Add skype repository
      yum_repository:
        name: skype-stable
        description: Skype YUM Repo
        baseurl: https://repo.skype.com/rpm/stable
        gpgcheck: true
        gpgkey: "https://repo.skype.com/data/SKYPE-GPG-KEY"

    - name: Install Skype
      dnf:
        name: skypeforlinux
        state: latest

    ## Install Microsoft Visual Studio Code
    - name: Add VS Code repository
      yum_repository:
        name: vscode
        description: VS Code YUM Repo
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"

    - name: Install VS Code
      dnf:
        name: code
        state: latest
